# version: "3"
services:

  # WEB
  nginx:
    build: docker/web/nginx
    restart: "${RESTART}"
    ports:
      - "${WEB_PORT}:80"
      - "${WEB_SSL_PORT}:443"
    volumes:
      - "${NGINX_CONF}:/etc/nginx/conf.d/default.conf"
      - "${PROJECT_DIR}:/var/www"
    links:
      - "php"
      - "mysql"
      - "mail"

  # APP
  php:
    build: docker/app/php
    restart: "${RESTART}"
    command: "php-fpm"
    ports:
      - "${PHP_PORT}:8000"
      - "8080:8080"
    volumes:
      - "${PHP_CONF}:/usr/local/etc/php/php.ini"
      - "${PROJECT_DIR}:/var/www"
    links:
      - "mysql"

  node_js:
    build: docker/app/nodejs
    restart: "${RESTART}"
    command: yarn run dev
    ports:
      - "${NODEJS_PORT}:${NODEJS_PORT}"
    volumes:
      - "${PROJECT_DIR}:/app"

  # DATABASE
  mysql:
    build: docker/database/mysql
    restart: "${RESTART}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - "${DB_DIR}/mysql:/var/lib/mysql"

  # MAIL
  mail:
    build: docker/mail/maildev
    restart: "${RESTART}"
    ports:
      - "${MAIL_PORT_D}:1080"
      - "1025:1025"

  redis:
    build: docker/cache/redis
    restart: "${RESTART}"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - "${CACHE_DIR}/redis:/data"

  # typesense:
  #   build: docker/search/typesense
  #   restart: "${RESTART}"
  #   command: "--data-dir /data --api-key=${SEARCH_API_KEY} --enable-cors"
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #     - "${TYPESENSE_PORT}:8108"
  #   volumes:
  #     - "${SEARCH_DIR}/elasticsearch:/usr/share/elasticsearch/data"
  #     - "${SEARCH_DIR}/typesense:/data"
  # UTILS
  adminer:
    image: adminer
    restart: "${RESTART}"
    ports:
      - "${ADMINER_PORT}:8080"
    volumes:
      - "${PHP_CONF}:/etc/php/7.4/cli/php.ini"
      - "${PHP_CONF}:/etc/php/7.4/fpm/php.ini"
      - "${PHP_CONF}:/usr/local/etc/php/conf.d/php.ini"
