FROM mysql
ENV MYSQL_ROOT_PASSWORD=root
# RUN mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS portfolio_laravel"
# RUN mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS portfolio_laravel_test"
CMD ["mysqld"]
STOPSIGNAL SIGTERM